#!/bin/bash
# Debtop
#
# This script is the main debtop script, responsible for starting the chrooted
# system and/or programs inside the chroot jail.
#
# Its settings MUST be on /opt/DebTop/etc/main.cf
#
# Author: Diego Lima <diego@diegolima.org>

PROGRAM="${1}"

test -f /opt/DebTop/etc/main.cf && . /opt/DebTop/etc/main.cf
test -f /opt/DebTop/etc/extra.cf && . /opt/DebTop/etc/extra.cf

createLoopDevice() {
	if ! [ -f /tmp/debtop-loop ]; then
		LOOPCNT=50
	else
		LOOPCNT=`cat /tmp/debtop-loop`
		LOOPCNT=$(($LOOPCNT+1))
	fi

	if ! [ -b ${LOOPDEVICE}${LOOPCNT} ]; then
		echo $LOOPCNT > /tmp/debtop-loop
		sudo mknod -m600 ${LOOPDEVICE}${LOOPCNT} b 7 $LOOPCNT
        fi
}

doMount() {
	# Check if we're using an alternate partition on the SD card
	if ! [ -z $SDPART ]; then
		sudo mount | grep $SDPART &>/dev/null
		if [ $? != 0 ]; then
			echo "Mounting $SDPART on $MEDIA"
			sudo mount $SDPART $MEDIA || exit 1
		else
			echo "$SDPART already mounted"
		fi
	fi

	if ! [ -f $DISK  ]; then
		xmessage "I could NOT find your Linux disk. Please check that it exists on $DISK" 
		exit 2
	fi
	
	sudo mount | grep $DEBROOT &>/dev/null
	if [ $? != 0 ]; then
		createLoopDevice

		# Check the filesystem for errors
		sudo fsck -p $DISK &>/dev/null
		if [ $? = 0 ]; then
			echo "Filesystem check completed. No errors found"
		elif [ $? = 1 ]; then
			echo "Filesystem contained errors but they've been fixed"
		else
			xmessage -buttons "Cancel:1,Mount Anyway:0" "Your image filesystem contain errors that cannot be corrected automatically. 
Please refer to DebTop wiki on how to manually fix the errors." || exit 6
		fi

		echo "Mounting $DISK on $DEBROOT using ${LOOPDEVICE}${LOOPCNT}"
		sudo mount -o loop=${LOOPDEVICE}${LOOPCNT},noatime,data=journal $DISK $DEBROOT
		if [ $? != 0 ]; then
			doUmount
			xmessage "Could NOT mount $DISK. Please check that your SD card is working."
			exit 3
		fi
	else
		echo "$DEBROOT is already mounted"
	fi
}
doUmount() {
	for i in `sudo mount|grep $DEBROOT|awk '{print $3}'|tac`; do
		sudo umount -l $i &> /dev/null
	done
}

sysChroot() {
	ACTION="sudo mount"
	MTOPTS="-o bind"

	test -f $DEBROOT/bin/sh 
	if [ $? != 0 ]; then
		xmessage "Your image does not contain a /bin/sh shell!"
		exit 5
	fi
	
	test -d $DEBROOT/proc || sudo mkdir -p $DEBROOT/proc
	sudo mount | grep $DEBROOT/proc &>/dev/null|| \
		sudo $ACTION $MTOPTS /proc $DEBROOT/proc &>/dev/null

	test -d $DEBROOT/dev || sudo mkdir -p $DEBROOT/dev
	sudo mount | grep $DEBROOT/dev &>/dev/null|| \
		sudo $ACTION $MTOPTS /dev  $DEBROOT/dev &>/dev/null
	
	test -d $DEBROOT/dev/pts || sudo mkdir -p $DEBROOT/dev/pts
	sudo mount | grep $DEBROOT/dev/pts &>/dev/null|| \
		sudo $ACTION $MTOPTS /dev/pts $DEBROOT/dev/pts &>/dev/null

	test -d $DEBROOT/dev/shm || sudo mkdir -p $DEBROOT/dev/shm
	sudo mount | grep $DEBROOT/dev/shm &>/dev/null|| \
		sudo $ACTION $MTOPTS /dev/shm $DEBROOT/dev/shm &>/dev/null

	test -d $DEBROOT/sys || sudo mkdir -p $DEBROOT/sys
	sudo mount | grep $DEBROOT/sys &>/dev/null|| \
		sudo $ACTION $MTOPTS /sys  $DEBROOT/sys &>/dev/null

	test -d $DEBROOT/tmp || sudo mkdir -p $DEBROOT/tmp
	sudo mount | grep $DEBROOT/tmp &>/dev/null|| \
		sudo $ACTION $MTOPTS /tmp  $DEBROOT/tmp &>/dev/null

	test -d $DEBROOT/var/tmp || sudo mkdir -p $DEBROOT/var/tmp
	sudo mount | grep $DEBROOT/var/tmp &>/dev/null|| \
		sudo $ACTION $MTOPTS /var/tmp $DEBROOT/var/tmp &>/dev/null

	test -d $DEBROOT/var/run/dbus || sudo mkdir -p $DEBROOT/var/run/dbus
	sudo mount | grep $DEBROOT/var/run/dbus &>/dev/null|| \
		sudo $ACTION $MTOPTS /var/run/dbus $DEBROOT/var/run/dbus &>/dev/null

	test -d $DEBROOT/media/sdcard || sudo mkdir -p $DEBROOT/media/sdcard
	sudo mount | grep $DEBROOT/media/sdcard &>/dev/null|| \
		sudo $ACTION /dev/block/vold/179:18 $DEBROOT/media/sdcard &>/dev/null

	test -d $DEBROOT/media/sdcard-ext || sudo mkdir -p $DEBROOT/media/sdcard-ext
	sudo mount | grep $DEBROOT/media/sdcard-ext &>/dev/null|| \
		sudo $ACTION /dev/block/vold/179:33 $DEBROOT/media/sdcard-ext &>/dev/null

	test -d $DEBROOT/home/adas || sudo mkdir -p $DEBROOT/home/adas
	sudo mount | grep $DEBROOT/home/adas &>/dev/null|| \
		sudo $ACTION $MTOPTS /home/adas $DEBROOT/home/adas
}

doRun() {
	local RUN="${1}"
	sudo chroot $DEBROOT dhclient &>/dev/null

	if ! [ -z $RUN ]; then
		sudo chroot $DEBROOT $RUN
	else
		sudo chroot $DEBROOT /usr/bin/lxterminal -e pdemenu
	fi
}

xhost + &>/dev/null

if [ "$PROGRAM" == "stop" ]; then
	echo "Stopping DebTop"
	doUmount
else
	echo "Starting DebTop"
	doMount
	sysChroot mount
	doRun "$PROGRAM"
fi
